version: "3"
services:
  hello-python:
    image: leopaillier/hello-python-random-error:1.0
    ports:
      - "5000:5000"
    labels:
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'hello-python-usm'
      com.datadoghq.tags.version: '1.0'
    environment:
      - DD_ENV=prod
      - DD_SERVICE=hello-python-usm
      - DD_VERSION=1.0
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=datadog
    depends_on:
      - datadog
  datadog:
    image: datadog/agent:latest
    ports:
      - "8126:8126"
    environment:
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS='env:prod'
      - DD_HOSTNAME=dd-docker-compose-host
      - DD_SYSTEM_PROBE_SERVICE_MONITORING_ENABLED=true
      - HOST_ROOT=/host/root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /:/host/root:ro
    cap_add:
     - SYS_ADMIN
     - SYS_RESOURCE
     - SYS_PTRACE
     - NET_ADMIN
     - NET_BROADCAST
     - NET_RAW
     - IPC_LOCK
     - CHOWN
    security_opt:
     - apparmor:unconfined